GOC = gcc
CFLAGS = -Wall -O2

1-define: 1-define.c
	${GOC} ${CFLAGS} -o $@ $<

1-const: 1-const.c
	${GOC} ${CFLAGS} -o $@ $<

1-2: 1-2.c
	${GOC} ${CELAGS} -o $@ $<

2-1: 2-1.c
2-2: 2-2.c
2-3: 2-3.c
2-4-double: 2-4-double.c
2-4-float: 2-4-float.c
showarg: showarg.c
sum: sum.c
array: array.c
array: array.c

	${GOC} ${CELAGS} -o $@ $<